### ISSUE TITLE
[Bug] Run command ".\scripts\post-init-setup.ps1" failed

### ISSUE THREAD

**Issue by blow-hey** [rpothin/servicebus-csharp-function-dataverse#3]
### Bug Description

**Issue1:**
Running `.\scripts\post-init-setup.ps1` after` azd init `will report the following error according to its README.
![image](https://user-images.githubusercontent.com/112381413/217698102-f6b8c761-77fc-4806-919f-dd85ec90fce1.png)
  
[Error code location1](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/scripts/post-init-setup.ps1#L242)
![image](https://user-images.githubusercontent.com/112381413/217735380-b60d4583-ea8b-4773-b8bf-e1237ffe81ef.png)
[Error code location2](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/scripts/post-init-setup.ps1#L340)
![image](https://user-images.githubusercontent.com/112381413/217735273-8c8c587e-9ff3-4f98-9a5c-abadf9086dc4.png)

**Issue2:**
After fix the above errors `Issue1` executing the command`.\scripts\post-init-setup.ps1` requires the `dataverseEnvironmentUrl`, we press `enter` according to the prompt and an error occurs after selecting `y` in the options that appear.

So, how to get the value of the `dataverseEnvironmentUrl`?  

![image](https://user-images.githubusercontent.com/112381413/217736488-4ceeec86-e478-4a56-b341-5a9aae33143e.png)

### Steps To Reproduce

1. Login with `az login` and `azd login`
2. Run Command `azd init --template rpothin/servicebus-csharp-function-dataverse`
3. Run Command `.\scripts\post-init-setup.ps1`

### Expected Behavior

Run Command `.\scripts\post-init-setup.ps1` successfully.

@rpothin  for notification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rpothin** [comment]
Hi @blow-hey,

Thank you very much for trying the template and for reporting such detailed bug.

I will do my best to try to help you 😊

## Issue 1 - Query filter issue running `az ad app list`

I have done some tests on my side (*without and with the latest available version of [Azure CLI - 2.45.0](https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.45.0)*), and unfortunately, I have not been able to reproduce the issue and I have not been able to make your suggestion work. You can find the result of my tests below.

**Could you share more details with me regarding the condition in which you are doing your tests please?** (OS, bash or pwsh, Azure CLI specific configuration...)

### GitHub Codespace - bash

#### Non-existing app registration

![image](https://user-images.githubusercontent.com/23240245/217986093-33d007e1-ae5c-486f-9019-72273257b1af.png)

#### Existing app registration

![image](https://user-images.githubusercontent.com/23240245/217985433-1ba6721d-966f-4148-9a1c-d467585c98c9.png)

### GitHub Codespace - pwsh

#### Non-existing app registration

![image](https://user-images.githubusercontent.com/23240245/217986197-249d2e2e-378a-484e-9744-e4fe913dd1be.png)

#### Existing app registration

![image](https://user-images.githubusercontent.com/23240245/217985549-ed51f2d4-4def-4749-b360-232a4c12ee5f.png)

### Windows laptop - Terminal - pwsh

#### Non-existing app registration

![image](https://user-images.githubusercontent.com/23240245/217986046-32166b3d-5889-420f-8330-f41f86e60336.png)

#### Existing app registration

![image](https://user-images.githubusercontent.com/23240245/217985938-cd220e67-0902-496d-a1a7-b248cacf6be9.png)

## Issue 2 - Get a `dataverseEnvironmentUrl`

It seems you are doing the test on a tenant where Power Platform administrators have restricted the creation of at least "Trial" type environments to platform administrators.

I can suggest few options in this situation:
- try other types of environments in the [.dataverse/environment-configuration.json](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/.dataverse/environment-configuration.json) configuration file - **for example, replace "Trial" by "Sandbox" or "Developer"**
- explore other options shared in the [Prerequisites > Power Platform](https://github.com/rpothin/servicebus-csharp-function-dataverse#power-platform) section of the README file - **for example, you could try to join the [Microsoft 365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program) and have a dedicated tenant for the Power Platform part of the test (*the template support Azure and Power Platform parts in different tenants*)**
- follow the process in your company to request a Power Platform environment for your tests. You will then be able to enter the URL of the environment when asked running the script.

I hope all these suggestions will help you move forward with your tests.

Have a great day.

**Comment by blow-hey** [comment]
Hi @rpothin,
About **issue1**, running this query command separately is no problem. But throughout the code, the result output through tsv is string, directly call the `$azureDeploymentAppRegistrationCreationResult[1]` parameter, the value we get is the second digit of id, as shown in the following figure. Please help to check and resolve it.
![image](https://user-images.githubusercontent.com/112381413/218056826-97730dc0-9c1d-47a8-9fa1-d453e3b9fe6f.png)

![image](https://user-images.githubusercontent.com/112381413/218031523-a9fd2afe-a1e3-476c-9ca5-c4cabf68a6bd.png)

About **issue2**, thanks for your suggestion, we have been able to get this URL.
Besides, please help update the READEME file for more details on how to get the `dataverseEnvironmentUrl`.

**Comment by rpothin** [comment]
Hi @blow-hey,

Regarding **issue 2**, I added a [Get the URL of a Dataverse environment](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/A3-GetDataverseEnvironmentUrl.md) documentation page referenced at 2 different places to help people find the value for `dataverseEnvironmentUrl`:
- [In the README](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/efe7238cb73dc2056d627cf18cf81100cbf3611f/README.md?plain=1#L55)
- In the [Setup and deployment of the solution](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/efe7238cb73dc2056d627cf18cf81100cbf3611f/docs/01-Quickstart.md?plain=1#L46) documentation page in a note regarding the execution of the `post-init-setup.ps1` PowerShell script

Please, let me know if you feel it will be enough to guide people on this part so we can close this issue.

Have a great day.

**Comment by blow-hey** [comment]
@rpothin Ok, it is detailed enough, I will close this issue.

**Comment by blow-hey** [comment]
@rpothin In README [GitHub configuration](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/03-GitHubConfiguration.md), the order of `gh secret set <secret name>` and `azd pipeline config --auth-type federated --principal-name <service principal name>` needs to be changed, because set secrets cannot be set without specifying repository.

Please help to update it in README [GitHub configuration](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/03-GitHubConfiguration.md).

**Comment by rpothin** [comment]
@blow-hey I am assuming your latest comment is regarding issue #4 not this one.
If I am right, can you copy - paste your comment in the other issue please.
Thank you in advance.

In the same time I will start working on the change 😉
