### ISSUE TITLE
[Bug] README Link issues

### ISSUE THREAD

**Issue by blow-hey** [rpothin/servicebus-csharp-function-dataverse#5]
### Bug Description

1.
Section [link1](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/00-Prerequisites.md#tools), [link2](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/03-GitHubConfiguration.md#initialize-github-configuration):
![image](https://user-images.githubusercontent.com/112381413/219608005-8358b95d-f070-4441-830f-fcb0779bdca8.png)
![image](https://user-images.githubusercontent.com/112381413/219608647-70b7ad17-30fc-42fb-acc5-f80f7e2cc547.png)

**Reason:**
Referenced file path error.

**Suggestion:**
Change the reference file path to `../scripts/post-init-setup.ps1`

2.
Section [link](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/01-Quickstart.md):
![image](https://user-images.githubusercontent.com/112381413/219609831-97dd541f-4993-4e4c-b247-49df988f8e97.png)
![image](https://user-images.githubusercontent.com/112381413/219610165-0b1889b1-d39e-4b05-94c7-cbc5d5b0844f.png)

**Reason:**
Referenced file path error.

**Suggestion:**
Change the reference file path to `../.dataverse/environment-configuration.json`

3.
Section [link](https://github.com/rpothin/servicebus-csharp-function-dataverse/blob/main/docs/02-TestTheSolution.md):
![image](https://user-images.githubusercontent.com/112381413/219610515-7767fe8d-b43d-4d98-8ef2-a938adf44ffb.png)
![image](https://user-images.githubusercontent.com/112381413/219610628-89d4e0fa-bde5-4a0a-8efe-651b7390460e.png)

**Reason:**
Referenced file path error.

**Suggestion:**
Change the reference file path to `../infra/main.parameters.json`

### Steps To Reproduce

@rpothin for notification.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rpothin** [comment]
Hey @blow-hey 👋🏼,

Thank you very much for finding these wrong links.
Here is the commit for the correction of this issue: [rpothin/servicebus-csharp-function-dataverse - c51de6](https://github.com/rpothin/servicebus-csharp-function-dataverse/commit/c51de63b49423daa0aef3ec9819c0c3f6787692d)

Please, let me know if the links seem ok now.
Have a great day.
Raphael

**Comment by blow-hey** [comment]
@rpothin Ok, thanks for your edit, I will close this issue.
Have a good day XD.
