### ISSUE TITLE
Updating/work-with this template for GHA and Azd Devcontainer feature.

### ISSUE THREAD

**Issue by v-xuto** [rpothin/servicebus-csharp-function-dataverse#7]
### Bug Description

We are updating this template to support new features in Github Action and Azd Devcontainer.

1. **For the Github Action feature:** We will remove two lines of code on container image and add GHA code after checkout step in the `.github/workflow/azure-dev.yml` file. (Shown as below)
![image](https://github.com/rpothin/servicebus-csharp-function-dataverse/assets/57166602/30f75053-bb66-4492-8baf-cc873fe60e7d)

2. **For the Azd Devcontainer feature:** We will remove `dockerfile` in `.devcontainer` folder and add the following code in `devcontainer.json` file,
```
"ghcr.io/azure/azure-dev/azd:latest": {}
```
and image also need to be add instead of build.
![image](https://github.com/rpothin/servicebus-csharp-function-dataverse/assets/57166602/ca7b16db-fb15-4d39-9dd7-b74fd2499751)

@rajeshkamal5050 , @r for notification.

### Steps To Reproduce

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rpothin** [comment]
Hi @v-xuto,

Thank you very much for reminding me to implement these changes.

I have done the work in the branch linked to the issue.
But I have not yet been able to test it - it seems the GitHub Actions service is in a disrupted state right now.

As soon as the tests will be done and I will be confident the changes do not introduce regressions, I will create a PR, merge everything to the **main** branch and create a new minor release 😊

I will update the issue when everything is completed.

**Comment by rpothin** [comment]
@v-xuto I have finally been able to complete the work on this item.
Don't hesitate to let me know if I missed something in your request or if you think I should make other adjustments based on the evolution of azd.
